spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/limitsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
limits:
  default-value: 100000.00
server:
  port: 8080\n